# Fully-customed latex working environment (TEX + GIT + EMACS + TMUX)
# emacs-base image + tex environment

# pull base ubuntu image
FROM givasile/emacs-docker:latest

# install apt-level packages
USER root
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install git texlive-full
USER givasile

ENTRYPOINT ["/bin/zsh"]